spring.application.name=atualizacliente

spring.datasource.url=jdbc:postgresql://db.poncio.dev:5432/atualizacliente
spring.datasource.username=postgres
spring.datasource.password=DB@2022
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect