spring.application.name=atualizacliente

spring.datasource.url=jdbc:postgresql://db.poncio.dev:5432/atualizacliente
spring.datasource.username=postgres
spring.datasource.password=DB@2022
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

AUTH.JWTSECRET=M&JkGie8y+Hh.xVYfD%qN:?K-{2?Fm)h}i2Np7VxnaS-[9C!X:RezE;B3T#V])S-
AUTH.JWTEXPMS=86400000

usuarios.permiteCadastro=false

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
cookie.domain.base-url=localhost